const ACTION_TYPES = {
    TOGGLE_LOADING: "TOGGLE_LOADING",
    TOGGLE_TAB_LOADING: "TOGGLE_TAB_LOADING",
    GET_MOVIES: "GET_MOVIES",
    GET_POPULAR_MOVIES: "GET_POPULAR_MOVIES",
    GET_TOP_RATED_MOVIES: "GET_TOP_RATED_MOVIES",
    GET_UPCOMING_MOVIES: "GET_UPCOMING_MOVIES",
    GET_RECOMMENDATIONS: "GET_RECOMMENDATIONS",
    GET_CASTS_MOVIE: "GET_CASTS_MOVIE",
    GET_POSTERS: "GET_POSTERS",
    GET_BACKDROPS: "GET_BACKDROPS",
    GET_MOVIE: "GET_MOVIE",
    SET_ACTIVE_TAB: "SET_ACTIVE_TAB",
    GET_VIDEOES: "GET_VIDEOES",
    TOGGLE_IS_SEARCH_MOVIE: "TOGGLE_IS_SEARCH_MOVIE",
    SET_TOTAL_PAGES: "SET_TOTAL_PAGES", 
    GET_SEARCH_TRENDS: "GET_SEARCH_TRENDS",
    GET_TOTAL_RESULTS: "GET_TOTAL_RESULTS",
    GET_SEARCH_MOVIES: "GET_SEARCH_MOVIES"
}

export default ACTION_TYPES;