const ACTION_TYPES = {
    TOGGLE_LOADING: "TOGGLE_LOADING",
    TOGGLE_TAB_LOADING: "TOGGLE_TAB_LOADING",
    GET_MOVIES: "GET_MOVIES",
    GET_POPULAR_MOVIES: "GET_POPULAR_MOVIES",
    GET_TOP_RATED_MOVIES: "GET_TOP_RATED_MOVIES",
    GET_UPCOMING_MOVIES: "GET_UPCOMING_MOVIES",
    GET_RECOMMENDATIONS: "GET_RECOMMENDATIONS",
    GET_CASTS_MOVIE: "GET_CASTS_MOVIE",
    GET_POSTERS: "GET_POSTERS",
    GET_BACKDROPS: "GET_BACKDROPS",
    GET_MOVIE: "GET_MOVIE",
    SET_ACTIVE_TAB: "SET_ACTIVE_TAB",
    GET_VIDEOES: "GET_VIDEOES",
    GET_PEOPLE: "GET_PEOPLE",
    GET_GENRES: "GET_GENRES",
    SET_TOTAL_PAGES: "SET_TOTAL_PAGES", 
    HANDLE_CARD_GROUP_ACTIVE_TAB: "HANDLE_CARD_GROUP_ACTIVE_TAB"
}

export default ACTION_TYPES;